#!/usr/bin/python
#
# -----------------------------------------------------------------------------------------------------
# Description
# -----------------------------------------------------------------------------------------------------
#
# This script is a CLI executable for meldmerge in OSX.
# With this script you can compare between two or three files.
#
# -----------------------------------------------------------------------------------------------------
# Requirements
# -----------------------------------------------------------------------------------------------------
#
# - meldmerge for OSX (https://github.com/yousseb/meld/releases/)
#
# -----------------------------------------------------------------------------------------------------
# Usage
# -----------------------------------------------------------------------------------------------------
#
# Copy this file in your /usr/local/bin/ directory, then execute:
# ./meld <file1> <file2> <file3>
#
# -----------------------------------------------------------------------------------------------------

import sys
import os
import subprocess
 
MELDPATH = "/Applications/Meld.app"
 
subprocess.call( ['open', '-W', '-a',  MELDPATH, '--args'] + map( os.path.abspath, sys.argv[1:] ) )
